apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace}}                                    
  labels:
    app: {{ .Values.app.name }}  
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 45
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: {{ .Values.app.name }}
      labels:
        app: {{ .Values.app.name }}
        ArcherID: "6268730"
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - env:
          - name: KEYVAULTCLIENTID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretKeyRef.name }}
                key: clientid
          - name: KEYVAULTCLIENTSECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretKeyRef.name }}
                key: clientsecret
          - name: KEYVAULTURI
            value: {{ .Values.keyvault.clienturi }}
          - name: SPRING_PROFILES_ACTIVE
            value: {{ .Values.springProfileActive }}
          name: {{ .Values.app.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources: 
            requests:
              cpu: 256m
              memory: 1G
            limits:
              cpu: 500m
              memory: 1G
      restartPolicy: Always